name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the server daemon image and run it
      run: docker build . --file Dockerfile --tag softhsm-daemon +%s) && docker run -d --name hsm softhsm-daemon
    - name: Build the client image and run it
      run: docker build . --file Dockerfile.client --tag softhsm-client && docker run --rm --link=hsm:hsm softhsm-client pkcs11-tool --module=/usr/local/lib/libpkcs11-proxy.so -L
